export const ActionTypes = {
    SET_TRACKS: 'SET TRACKS',
    ADD_TRACKS_TO_PLAYLIST: 'ADD TRACK TO PLAYLIST',
    REMOVE_TRACKS_FROM_PLAYLIST: 'REMOVE TRACK FROM PLAYLIST',
    SEARCH_TRACKS: "SEARCH TRACKS",
    SEARCH_RESULTS: "SEARCH RESULTS",
    ADD_TRACKS_TO_PLAYLIST_FROM_SEARCH: "ADD TRACKS TO PLAYLIST FROM SEARCH",
    SET_SHOW: "SET SHOW"
}